-- Generated by nwg-displays on 2026-09-23 at 20:40:47. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@60.0",
    position = "0x0",
    scale = 1.666667,
    vrr = 0
})
